[package]
name = "atxpkg"
version = "10.2.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
clap = { version = "4.5.18", features = ["derive"] }
filetime = "0.2.25"
glob = "0.3.1"
hex = "0.4.3"
indicatif = "0.17.8"
itertools = "0.13.0"
lazy-regex = "3.3.0"
log = "0.4.22"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
md-5 = "0.10.6"
rayon = "1.10.0"
reqwest = { version = "0.12.7", features = ["blocking", "native-tls-vendored", "rustls-tls"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
simplelog = "0.12.2"
tempfile = "3.12.0"
time = { version = "0.3.36", features = ["local-offset", "macros"] }
walkdir = "2.5.0"
zip = { version = "2.2.0", features = ["time"] }

[profile.release.package."*"]
debug = false

[profile.release]
debug = "line-tables-only"
codegen-units = 1
lto = true
