#!/usr/bin/python3

'''
Make Asterix package.

Usage:
  mkpkg <name> <version>
'''

from version import __version__

import docopt
import os
import subprocess
import datetime


def main():
	args = docopt.docopt(__doc__, version=__version__)

	name = args['<name>']
	version = args['<version>']

	if version.endswith('a'):
		version += datetime.datetime.now().strftime('%Y%m%d%H%M%S')
	#endif

	pkgname = '%s-%s.atxpkg.zip' % (name, version)

	if os.path.isfile(pkgname):
		os.remove(pkgname)
	#endif

	subprocess.call('rd /s /q build', shell=True)
	subprocess.call('rd /s /q dist', shell=True)
	subprocess.call('python setup.py install --prefix=dist', shell=True)

	subprocess.call('md pkg', shell=True)
	subprocess.call('md pkg\\atx300\\%s' % name, shell=True)
	subprocess.call('cp -av dist/* pkg/atx300/%s' % name, shell=True)
	subprocess.call('cp atxpkg_backup pkg/.atxpkg_backup', shell=True)

	os.chdir('pkg')
	subprocess.call('zip -r ../%s .' % pkgname, shell=True)
	os.chdir('..')

	subprocess.call('rd /s /q pkg', shell=True)

	subprocess.call('pscp %s radek@podgorny.cz:public_html/atxpkg/' % pkgname, shell=True)
#enddef


if __name__ == '__main__':
	main()
#endif
