#!/bin/sh
set -e -x
#python -m unittest
#coverage run -m unittest
#coverage run -m pytest $@  # TODO: fix this
pipenv run coverage run -m pytest test*py

COVERAGE_REPORT_ARGS="--omit=*/virtualenvs/*"
rm -rf htmlcov
pipenv run coverage html ${COVERAGE_REPORT_ARGS}
pipenv run coverage report ${COVERAGE_REPORT_ARGS}
